---
- hosts: webservers

  vars:
     server_name: test.askvietnamese.vn
     app_dir: /opt/bitnami/apps/askvietnamese_ansible
     project_root: /opt/bitnami/apps/askvietnamese_ansible/htdocs
     bitnami_vhosts: /opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf

  sudo: yes
  tasks:
   - name: create /opt/bitnami/apps/askvietnamese_ansible/conf directory 
     file: dest="{{ app_dir }}/conf"   state=directory recurse=yes

   - name: Clone git repository
     git: 
        dest={{ project_root }}
        repo='https://github.com/GodStorm91/askvietnamese'
        update=no

   - name: Install composer
     shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

   - name: composer install
     composer:
        command: install
        working_dir: "{{ project_root }}"
     sudo: no

   - name: config vhosts-app
     tags:
        - nginx
     become: true
     template:
        src: templates/askvietnamese-app.conf
        dest: "{{ app_dir }}/conf/{{ server_name }}-app.conf"

   - name: config vhosts
     tags:
        - nginx
     become: true 
     template:
        src: templates/askvietnamese-vhosts.conf
        dest: "{{ app_dir }}/conf/{{ server_name }}-vhosts.conf"
  
   - name: config prefix
     tags:
        - nginx
     become: true
     template:
       src: templates/askvietnamese-prefix.conf
       dest: "{{ app_dir }}/conf/{{ server_name }}-prefix.conf"
  
   - name: appends to vhosts
     tags: 
       - nginx 
     lineinfile: 
       path: /opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf
       line: include "{{app_dir}}/conf/{{ server_name }}-vhosts.conf";

   - name: restart nginx
     tags:
       - nginx
     shell: /opt/bitnami/ctlscript.sh restart nginx
     sudo: yes

   - name: update source to the newest
     tags:
      - git-pull
     shell: 'cd "{{ project_root }}" && git checkout {{ branch }} && git pull'

