---
- hosts: askvietnamese

  vars:
     server_name: test.askvietnamese.vn
     app_dir: /opt/bitnami/apps/askvietnamese_ansible
     project_root: /opt/bitnami/apps/askvietnamese_ansible/htdocs
     

  sudo: yes
  tasks:
   - name: create /opt/bitnami/apps/askvietnamese_ansible/conf directory 
     file: dest="{{ app_dir }}/conf"   state=directory recurse=yes

   - name: Clone git repository
     git: 
        dest={{ project_root }}
        repo='https://github.com/GodStorm91/askvietnamese'
        update=no

   - name: Install composer
     shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

   - name: composer install
     composer:
        command: install
        working_dir: "{{ project_root }}"
     sudo: no

   - name: config vhosts-app
     become: true
     template:
        src: templates/askvietnamese-app.conf
        dest: "{{ app_dir }}/conf/{{ server_name }}-app.conf"

   - name: config vhosts
     become: true 
     template:
        src: templates/askvietnamese-vhosts.conf
        dest: "{{ app_dir }}/conf/{{ server_name }}-vhosts.conf"
  
   - name: config prefix
     become: true
     template:
       src: templates/askvietnamese-prefix.conf
       dest: "{{ app_dir }}/conf/{{ server_name }}-prefix.conf"
